stages:
  - TEST

cache:
  paths:
    - vendor/

UNIT TEST:
  stage: TEST
  script:
    - composer install
    - phpunit
  tags:
    - php

LINT:
  stage: TEST
  script:
    - phpcs -p --standard=PSR2 src --ignore=src/Database/**,src/Config/* --runtime-set ignore_errors_on_exit 1 --runtime-set ignore_warnings_on_exit 1
  tags:
    - php
